version: "3.3"
services:
  backend:
    container_name: geekcamp_go
    build: ./go
    volumes:
      - ./go/src:/app
    command: sh -c "/wait && go run main.go"
    tty: true
    ports:
      - "8083:80"

  mysql:
    container_name: geekcamp_mysql
    build: ./mysql
    ports:
      - "33060:3306"
    volumes:
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ROOT_PASSWORD: root-pw
      MYSQL_DATABASE: backend_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password
