swagger: "2.0"
info:
  version: "1.1"
  title: "GeekCamp"
  description: "geekcamp用API"
tags:
  - name: "task"

paths:
  /task:
    get:
      tags:
        - "task"
      summary: "タスクをランダムで返す"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      responses:
        200:
          description: "response"
          schema:
            type: "array"
            items:
              type: "object"
              properties:
                task_id:
                  type: "integer"
                detail:
                  type: "string"
                is_available:
                  type: "boolean"

    post:
      tags:
        - "task"
      summary: "達成したタスクのログを取る"
      description: ""
      consumes:
        - "application/json"
      produces:
        - "application/json"
      parameters:
        - in: "body"
          name: "body"
          required: true
          description: "response"
          schema:
            type: "object"
            properties:
              task_id:
                type: "integer"

      responses:
        200:
          description: OK
